title: Site

tabs:
  content:
    icon: dashboard
    columns:
      - width: 1/3
        sections:
          listed:
            headline: Listed pages
            type: pages
            status: listed
          unlisted:
            headline: Unlisted pages
            type: pages
            status: unlisted
          drafts:
            headline: Drafts
            type: pages
            status: draft


      - width: 2/3
        sections:
        fields:
          address:
            label: Adres
            type: text
          email:
            label: Email
            type: text
          socials:
            label: Socials
            type: structure
            columns:
              social:
                width: 1/4
              url:
                width: 1/2
            fields:
              social:
                type: select
                options:
                  facebook: Facebook
                  instagram: Instagram
                  linkedin: LinkedIn
                  youtube: YouTube
                  pinterest: Pinterest
                  reddit: Reddit
                  kdg: KdG Website
              url:
                type: url

          openhoursTitle:
            label: Openingsuren titel
            type: text
          openhoursKdGTitle:
            label: Openingsuren intern titel
            type: text
          openhoursKdGText:
            label: Openingsuren intern uren
            type: text
          openhoursExternTitle:
            label: Openingsuren extern titel
            type: text
          openhoursExternText:
            label: Openingsuren extern uren
            type: text

          navigationTitle:
            label: Navigatie titel
            type: text
          navigationLinks:
            label: Menu items
            type: structure
            columns:
              anchor:
                width: 1/2
              page:
                width: 1/2
            fields:
              anchor:
                label: Anker
                type: text
              page:
                label: Pagina
                type: pages
          
          infoTitle:
            label: Info titel
            type: text
          infoLinks:
            label: Andere pagina's
            type: structure
            columns:
              anchor:
                width: 1/2
              page:
                width: 1/2
            fields:
              anchor:
                label: Anker
                type: text
              page:
                label: Pagina
                type: pages
          
          kdgImage:
            label: KdG logo
            type: files
          provinceAntwerpImage:
            label: Provincie Antwerp logo
            type: files
  settings:
    icon: cog
    fields:
      fablabLogo:
        label: Fablab logo
        type: files
        max: 1

      flagImage:
        label: Vlaggetje taal
        type: files
        max: 1